### ISSUE TITLE
Cross-Origin Request blocked

### ISSUE THREAD

**Issue by robertvandeneynde** [vikhyat/latex-to-unicode#15]
When testing the app, I get this error in the js console (translated from French): 

Cross-Origin Request blocked: the policy « Same Origin » does not permit to consult the distant resource on http://app.vikhyat.net/latex_to_unicode/%5Cmathbb%7BR%7D. Reason : header CORS « Access-Control-Allow-Origin » is missing.

**Comment by vikhyat** [comment]
Should be fixed now.

**Comment by MaxGaukler** [comment]
It still happens for me in Firefox, I get roughly the same message in german.
